#name: "Master branch : CI & CD"
#
## íŠ¸ë¦¬ê±° ì¢…ë¥˜ ( í•´ë‹¹ íŠ¸ë¦¬ê±°ê°€ ë°œìƒí• ë•Œ ì•„ë˜ì˜ ì›Œí¬í”Œë¡œìš°ê°€ ì‹¤í–‰ë¨ )
#on:
##  workflow_dispatch:    # Github Actionì—ì„œ ìˆ˜ë™ìœ¼ë¡œ ì›Œí¬í”Œë¡œìš° ì‹¤í–‰ ê°€ëŠ¥
##  push:                 # push ì´ë²¤íŠ¸ ë°œìƒ ì‹œ
##    branches:
##      - master
#
#
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      # ì‘ì—… ì •ë³´
#      - name: info
#        run: |
#          echo "ğŸ‰ ${{ github.event_name }} event."
#          echo "${{ github.repository }} > ${{ github.ref }}."
#
#
#
#
#
#
#      # ì‘ì—… ì¢…ë£Œ
#      - name: Done.
#        run: echo "ì‘ì—… ìƒíƒœ {:} ${{ job.status }}."
