name: "branch manager"

# brach ìƒì„± & ìˆ˜ì • & ì‚­ì œ ê´€ë¦¬
on:
  workflow_dispatch:    # Github Actionì—ì„œ ìˆ˜ë™ìœ¼ë¡œ ì›Œí¬í”Œë¡œìš° ì‹¤í–‰ ê°€ëŠ¥
#  branch_protection_rule:
#    types: [created, deleted, edited]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # ì‘ì—… ì •ë³´
      - name: branch info
        run: |
          echo "ğŸ‰ ${{ github.event_name }} event."
          echo "${{ github.repository }} > ${{ github.ref }}."






      # ì‘ì—… ì¢…ë£Œ
      - name: Done.
        run: echo "ì‘ì—… ìƒíƒœ {:} ${{ job.status }}."

